[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
testpaths = tests
addopts = -ra
markers =
    unit: unit tests
    api: api tests
    smoke: smoke tests
