# Generated by Django 4.2.28 on 2026-02-04 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('avatar', models.JSONField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('subscription_status', models.CharField(default='none', max_length=50)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('plan', models.CharField(default='free', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover', models.JSONField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('view_settings', models.JSONField(default=dict)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('friends', 'Friends Only'), ('public', 'Public')], default='private', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notebooks',
            },
        ),
        migrations.CreateModel(
            name='StripeProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product_type', models.CharField(max_length=50)),
                ('stripe_product_id', models.CharField(max_length=255)),
                ('stripe_price_id', models.CharField(max_length=255)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'stripe_products',
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.CharField(max_length=50)),
                ('s3_key', models.CharField(max_length=1024)),
                ('mime', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('uploaded', 'Uploaded'), ('confirmed', 'Confirmed'), ('expired', 'Expired'), ('failed', 'Failed')], default='issued', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upload_sessions',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_checkout_session_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(default='jpy', max_length=10)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stripeproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchases',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('diary', 'Diary'), ('schedule', 'Schedule'), ('free', 'Free')], default='diary', max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('scene_data', models.JSONField(default=dict)),
                ('assets', models.JSONField(default=dict)),
                ('used_sticker_ids', models.JSONField(default=list)),
                ('preview', models.JSONField(blank=True, null=True)),
                ('export', models.JSONField(blank=True, null=True)),
                ('layout_mode', models.CharField(default='auto', max_length=20)),
                ('layout_settings', models.JSONField(default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pages',
            },
        ),
        migrations.CreateModel(
            name='NotebookPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.notebook')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.page')),
            ],
            options={
                'db_table': 'notebook_pages',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='notebook',
            name='pages',
            field=models.ManyToManyField(related_name='notebooks', through='core.NotebookPage', to='core.page'),
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friendships',
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friend_requests',
            },
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('tags', models.JSONField(default=list)),
                ('favorite', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_system', models.BooleanField(default=False)),
                ('png', models.JSONField()),
                ('thumb', models.JSONField(blank=True, null=True)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('style', models.JSONField(default=dict)),
                ('crop_source', models.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stickers',
                'indexes': [models.Index(fields=['owner', 'favorite'], name='stickers_owner_i_05d317_idx'), models.Index(fields=['owner', 'last_used_at'], name='stickers_owner_i_293579_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['owner', 'date'], name='pages_owner_i_57f19d_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['owner', 'type'], name='pages_owner_i_0dcf69_idx'),
        ),
        migrations.AddIndex(
            model_name='notebookpage',
            index=models.Index(fields=['notebook', 'position'], name='notebook_pa_noteboo_f96685_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notebookpage',
            unique_together={('notebook', 'page')},
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['user1', 'user2'], name='friendships_user1_i_16f860_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('user1', 'user2')},
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('requester', 'target')},
        ),
    ]
