# Generated by Django 4.2.28 on 2026-02-07 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], default='monthly', max_length=20)),
                ('start_date', models.DateField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('scene_data', models.JSONField(blank=True, default=dict)),
                ('assets', models.JSONField(blank=True, default=dict)),
                ('events_data', models.JSONField(blank=True, default=dict)),
                ('preview', models.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'schedules',
                'indexes': [models.Index(fields=['owner', 'type', 'start_date'], name='schedules_owner_i_3b9707_idx')],
                'unique_together': {('owner', 'type', 'start_date')},
            },
        ),
    ]
