# Generated by Django 4.2.28 on 2026-02-24 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='StripeProduct',
        ),
    ]
