# Generated by Django 4.2.28 on 2026-02-25 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_purchase_delete_stripeproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='guest_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='uploadsession',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('user__isnull', False), ('guest_id__isnull', True)), models.Q(('user__isnull', True), ('guest_id__isnull', False)), _connector='OR'), name='uploadsession_owner_user_or_guest'),
        ),
    ]
