"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import environ
from datetime import timedelta




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#DATABASE_custom=True -> DATABASE_URLを使って接続

env = environ.Env(
    DEBUG=(bool, False),
)

# ローカルで "python manage.py runserver" する時だけ .env を読む（本番は読まない）
if os.path.exists(BASE_DIR / ".env"):
    environ.Env.read_env(BASE_DIR / ".env")

# 1) 環境の判定（ここが分岐の軸）
APP_ENV = env.str("APP_ENV", default="local")  # local / docker / apprunner / prod など好きに
DEBUG = env.bool("DEBUG", default=(APP_ENV == "local"))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default="dummy-key")
# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = env('DEBUG')

# App Runnerのデフォルトドメインや自分のドメインを環境変数から読み込む
# ALLOWED_HOSTS = ['*'] は本番ではNG
#ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1','192.168.3.4'])
raw_allowed_hosts = env('ALLOWED_HOSTS', default='localhost,127.0.0.1')
ALLOWED_HOSTS = [h.strip().replace('"', '').replace("'", "") for h in raw_allowed_hosts.split(',')]
#ALLOWED_HOSTS=['*']
# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'core',
    'storages',
    'djangorestframework_camel_case',  # ★これを追加
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # ★これを追加
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

DATABASE_custom = env.bool('DATABASE_custom', default=True)
if DEBUG==False:
    DATABASE_custom=True
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
if DATABASE_custom:
    # 3. データベース設定 (Neon対応)
    # env.db() は DATABASE_URL = postgres://user:pass@host/db を自動解析します
    DATABASES = {
        'default': env.db('DATABASE_URL') 
    }
    """
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    """
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'postgres',
            'USER': 'postgres',
            'PASSWORD': 'postgres',
            'HOST': 'db',  # docker-compose.ymlのサービス名「db」を指定
            'PORT': '5432',
        }
    }
    
# 4. セキュリティ設定 (本番環境のみ有効化)
if not DEBUG:
    # App RunnerはALB経由でHTTPSを受け取るため
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # HSTS設定
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # 5. 静的ファイルの設定 (App Runner/S3用)
    # App Runnerでは管理画面のCSSなどが消えやすいため、WhiteNoiseの利用も検討してください
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

else:
    STATIC_URL = '/static/'
    # 2. collectstaticでファイルが集まる場所（コンテナ内のパス）
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')



# --- 2. CORS (Cross Origin Resource Sharing) ---
# Next.js (localhost:3000) からのアクセスを許可
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://192.168.3.4:3000",
    "https://gnfhrmjdwy.ap-northeast-1.awsapprunner.com",
    "https://api.memocho.link",
    "https://memocho.link",
]
# 必要に応じて Credentials (Cookieなど) を許可
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',  # ★ これが重要
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_ALLOW_ALL_ORIGINS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://192.168.3.4:8080",
    'https://gnfhrmjdwy.ap-northeast-1.awsapprunner.com', 
    'https://api.memocho.link',
    'https://memocho.link']


# --- 3. DRF Settings ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication', # JWT推奨
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'djangorestframework_camel_case.render.CamelCaseJSONRenderer',
        'djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer',
        'rest_framework.renderers.JSONRenderer',
    ),
    # パーサー（Camel -> Snake）
    'DEFAULT_PARSER_CLASSES': (
        'djangorestframework_camel_case.parser.CamelCaseJSONParser',
        'djangorestframework_camel_case.parser.CamelCaseFormParser',
        'djangorestframework_camel_case.parser.CamelCaseMultiPartParser',
        'rest_framework.parsers.JSONParser',
    ),

    # フロントエンドが camelCase なので、入出力で変換するライブラリを入れると便利ですが
    # 今回はモデル定義に集中するため省略します。
}


# --- 4. AWS S3 Settings (Boto3用) ---
AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = env('AWS_S3_REGION', default='ap-northeast-1')
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
# S3のオブジェクトパラメータ設定
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400', # キャッシュ有効期限
}
#
#DEFAULT_FILE_STORAGE = os.getenv('DEFAULT_FILE_STORAGE', 'django.core.files.storage.FileSystemStorage')
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
    # 'ACL': 'public-read' <-- これがあれば削除してください
}
AWS_DEFAULT_ACL = None
# 署名付きURLを強制する設定
AWS_QUERYSTRING_AUTH = False
AWS_S3_FILE_OVERWRITE = False
AWS_QUERYSTRING_EXPIRE = 3600  # URLの有効期限（秒）
AWS_S3_SIGNATURE_VERSION = 's3v4'  # 最新の署名形式を使用
#CloudFront Settings
CLOUDFRONT_DOMAIN = env("CLOUDFRONT_DOMAIN")  # 例: dxxxxxxx.cloudfront.net
CLOUDFRONT_PUBLIC_KEY_ID = env("CLOUDFRONT_PUBLIC_KEY_ID")  # Public key ID
# 第一引数に環境変数名、defaultにNoneを指定
raw_key = env("CLOUDFRONT_PRIVATE_KEY", default=None)
# キーが存在する場合のみ改行コードの置換処理を行う
CLOUDFRONT_PRIVATE_KEY = raw_key.replace('\\n', '\n') if raw_key else None
CLOUDFRONT_URL_EXPIRES_SECONDS = int(env("CLOUDFRONT_URL_EXPIRES_SECONDS", default=3600))  # 署名付きURLの有効期限（秒）



# --- 5. Custom User Model ---
AUTH_USER_MODEL = 'core.User'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "querystring_auth": True,       # 署名付きURLを有効化
            "querystring_expire": 3600,    # 有効期限（1時間）
            "signature_version": "s3v4",   # 最新の署名バージョン
        },
    },
    "staticfiles": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    "OPTIONS": {
            "querystring_auth": False,  # ★ここをFalseに！
            "file_overwrite": False,
        },
    },
}