# Generated by Django 4.2.28 on 2026-03-04 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user_style', models.CharField(choices=[('user', 'User'), ('guest', 'Guest')], db_index=True, default='user', max_length=10)),
                ('guest_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('slot_index', models.PositiveIntegerField()),
                ('image_original_url', models.URLField(max_length=2048)),
                ('image_background_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('image_foreground_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('material_params', models.JSONField(blank=True, default=dict)),
                ('style_config', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'exhibits',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user_style', models.CharField(choices=[('user', 'User'), ('guest', 'Guest')], db_index=True, default='user', max_length=10)),
                ('guest_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('layout_cols', models.PositiveIntegerField(default=3)),
                ('layout_rows', models.PositiveIntegerField(default=4)),
                ('is_public', models.BooleanField(default=False)),
                ('cover_render_url', models.URLField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'galleries',
            },
        ),
    ]
