# Generated by Django 4.2.28 on 2026-03-04 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MiniatureMuseum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibits', to='MiniatureMuseum.gallery'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exhibits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['user_style', 'created_at'], name='galleries_user_st_0adc86_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['owner', 'created_at'], name='galleries_owner_i_55e7a5_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['guest_id', 'created_at'], name='galleries_guest_i_b91e03_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['slug'], name='galleries_slug_92bf10_idx'),
        ),
        migrations.AddConstraint(
            model_name='gallery',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('owner__isnull', False), ('user_style', 'user'), models.Q(('guest_id__isnull', True), ('guest_id', ''), _connector='OR')), ('user_style', 'guest'), _connector='OR'), name='gallery_user_style_user_requires_owner'),
        ),
        migrations.AddConstraint(
            model_name='gallery',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('owner__isnull', True), ('user_style', 'guest'), ('guest_id__isnull', False), models.Q(('guest_id', ''), _negated=True)), ('user_style', 'user'), _connector='OR'), name='gallery_user_style_guest_requires_guest_id'),
        ),
        migrations.AddConstraint(
            model_name='gallery',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('user_style', 'guest')), fields=('guest_id',), name='uniq_active_Gallery_per_guest'),
        ),
        migrations.AddIndex(
            model_name='exhibit',
            index=models.Index(fields=['gallery', 'slot_index'], name='exhibits_gallery_713b49_idx'),
        ),
        migrations.AddIndex(
            model_name='exhibit',
            index=models.Index(fields=['user_style', 'created_at'], name='exhibits_user_st_9264ce_idx'),
        ),
        migrations.AddIndex(
            model_name='exhibit',
            index=models.Index(fields=['owner', 'created_at'], name='exhibits_owner_i_673217_idx'),
        ),
        migrations.AddIndex(
            model_name='exhibit',
            index=models.Index(fields=['guest_id', 'created_at'], name='exhibits_guest_i_4eb848_idx'),
        ),
        migrations.AddConstraint(
            model_name='exhibit',
            constraint=models.CheckConstraint(check=models.Q(('slot_index__gte', 0), ('slot_index__lte', 11)), name='exhibit_slot_index_0_11'),
        ),
        migrations.AddConstraint(
            model_name='exhibit',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('owner__isnull', False), ('user_style', 'user'), models.Q(('guest_id__isnull', True), ('guest_id', ''), _connector='OR')), ('user_style', 'guest'), _connector='OR'), name='exhibit_user_style_user_requires_owner'),
        ),
        migrations.AddConstraint(
            model_name='exhibit',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('owner__isnull', True), ('user_style', 'guest'), ('guest_id__isnull', False), models.Q(('guest_id', ''), _negated=True)), ('user_style', 'user'), _connector='OR'), name='exhibit_user_style_guest_requires_guest_id'),
        ),
        migrations.AddConstraint(
            model_name='exhibit',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('gallery', 'slot_index'), name='uniq_active_exhibit_slot_per_gallery'),
        ),
    ]
