/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/guest/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_guest_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description ユーザー新規登録 */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exhibits/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exhibits_list"];
        put?: never;
        post: operations["exhibits_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exhibits/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exhibits_retrieve"];
        put: operations["exhibits_update"];
        post?: never;
        delete: operations["exhibits_destroy"];
        options?: never;
        head?: never;
        patch: operations["exhibits_partial_update"];
        trace?: never;
    };
    "/api/galleries/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["galleries_list"];
        put?: never;
        post: operations["galleries_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/galleries/{gallery_id}/exhibits/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description ネスト型: Exhibit追加（空枠に追加） */
        post: operations["galleries_exhibits_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/galleries/{gallery_id}/exhibits/{slot_index}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description ネスト型: slot_index 指定で作成 or 置換（推奨） */
        put: operations["galleries_exhibits_update"];
        post?: never;
        /** @description ネスト型: slot_index 指定で作成 or 置換（推奨） */
        delete: operations["galleries_exhibits_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/galleries/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["galleries_retrieve"];
        put: operations["galleries_update"];
        post?: never;
        delete: operations["galleries_destroy"];
        options?: never;
        head?: never;
        patch: operations["galleries_partial_update"];
        trace?: never;
    };
    "/api/galleries/g/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["galleries_g_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 自分のプロフィール取得・更新 */
        get: operations["me_retrieve"];
        /** @description 自分のプロフィール取得・更新 */
        put: operations["me_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description 自分のプロフィール取得・更新 */
        patch: operations["me_partial_update"];
        trace?: never;
    };
    "/api/notebooks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["notebooks_list"];
        put?: never;
        post: operations["notebooks_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notebooks/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["notebooks_retrieve"];
        put: operations["notebooks_update"];
        post?: never;
        delete: operations["notebooks_destroy"];
        options?: never;
        head?: never;
        patch: operations["notebooks_partial_update"];
        trace?: never;
    };
    "/api/notebooks/{id}/pages/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["notebooks_pages_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pages/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pages_list"];
        put?: never;
        post: operations["pages_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pages/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pages_retrieve"];
        put: operations["pages_update"];
        post?: never;
        delete: operations["pages_destroy"];
        options?: never;
        head?: never;
        patch: operations["pages_partial_update"];
        trace?: never;
    };
    "/api/schedules/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["schedules_list"];
        put?: never;
        post: operations["schedules_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["schedules_retrieve"];
        put: operations["schedules_update"];
        post?: never;
        delete: operations["schedules_destroy"];
        options?: never;
        head?: never;
        patch: operations["schedules_partial_update"];
        trace?: never;
    };
    "/api/stickers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stickers_list"];
        put?: never;
        post: operations["stickers_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stickers/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stickers_retrieve"];
        put: operations["stickers_update"];
        post?: never;
        delete: operations["stickers_destroy"];
        options?: never;
        head?: never;
        patch: operations["stickers_partial_update"];
        trace?: never;
    };
    "/api/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/{action}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description S3アップロード用のURL発行または完了確認を行います。 */
        post: operations["uploads_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AssetRef: {
            kind: components["schemas"]["KindEnum"];
            /** @description localならblobURI/uuid, remoteならS3 key/URL */
            key: string;
            mime?: string | null;
            width?: number | null;
            height?: number | null;
            sha256?: string | null;
            size?: number | null;
            filename?: string | null;
            /** @description thumb, medium などのバリエーション */
            variants?: {
                [key: string]: components["schemas"]["AssetRefLite"];
            };
            source?: {
                [key: string]: unknown;
            };
        };
        AssetRefLite: {
            kind: components["schemas"]["KindEnum"];
            /** @description localならblobURI/uuid, remoteならS3 key/URL */
            key: string;
            mime?: string | null;
            width?: number | null;
            height?: number | null;
            sha256?: string | null;
        };
        ExcalidrawSceneData: {
            /** @description Excalidrawの図形要素（Rectangle, Arrow, Text等）の配列 */
            elements?: {
                [key: string]: unknown;
            }[];
            /** @description 画面表示に関する設定（theme, scrollX, scrollY, zoom等） */
            appState?: {
                [key: string]: unknown;
            };
        };
        /** @description 展示物（編集/管理用）。画像はS3 URL（string）を想定。 */
        Exhibit: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            gallery: string;
            /** Format: uuid */
            readonly owner: string | null;
            readonly guestId: string | null;
            slotIndex: number;
            /** Format: uri */
            imageOriginalUrl: string;
            /** Format: uri */
            imageCutoutPngUrl?: string | null;
            materialParams?: unknown;
            style?: string;
            title?: string;
            description?: string;
            /** Format: date-time */
            readonly createdAt: string;
            /** Format: date-time */
            readonly updatedAt: string;
        };
        /** @description 公開閲覧用：owner/guest_id などは返さない。 */
        ExhibitPublic: {
            /** Format: uuid */
            readonly id: string;
            readonly slotIndex: number;
            /** Format: uri */
            readonly imageOriginalUrl: string;
            /** Format: uri */
            readonly imageCutoutPngUrl: string | null;
            readonly materialParams: unknown;
            readonly style: string;
            readonly title: string;
            readonly description: string;
            /** Format: date-time */
            readonly createdAt: string;
            /** Format: date-time */
            readonly updatedAt: string;
        };
        /** @description ギャラリー（編集/管理用）。retrieveではexhibitsも返す。 */
        Gallery: {
            /** Format: uuid */
            readonly id: string;
            slug: string;
            userStyle?: components["schemas"]["UserStyleEnum"];
            /** Format: uuid */
            readonly owner: string | null;
            readonly guestId: string | null;
            title?: string;
            layoutCols?: number;
            layoutRows?: number;
            isPublic?: boolean;
            /** Format: uri */
            coverRenderUrl?: string | null;
            /** Format: date-time */
            readonly createdAt: string;
            /** Format: date-time */
            readonly updatedAt: string;
            readonly exhibits: components["schemas"]["Exhibit"][];
        };
        GalleryPublic: {
            /** Format: uuid */
            readonly id: string;
            readonly slug: string;
            readonly title: string;
            readonly layoutCols: number;
            readonly layoutRows: number;
            readonly isPublic: boolean;
            /** Format: uri */
            readonly coverRenderUrl: string | null;
            /** Format: date-time */
            readonly createdAt: string;
            /** Format: date-time */
            readonly updatedAt: string;
            readonly exhibits: components["schemas"]["ExhibitPublic"][];
        };
        GuestIssueResponse: {
            guestId: string;
        };
        /**
         * @description * `local` - local
         *     * `remote` - remote
         * @enum {string}
         */
        KindEnum: "local" | "remote";
        Notebook: {
            /** Format: uuid */
            readonly id: string;
            cover?: components["schemas"]["AssetRef"] | null;
            readonly pageIds: string[];
            schemaVersion?: number;
            /** Format: date-time */
            readonly createdAt: string;
            /** Format: date-time */
            readonly updatedAt: string;
            /** Format: date-time */
            deletedAt?: string | null;
            title: string;
            description?: string;
            tags?: unknown;
            viewSettings?: unknown;
            visibility?: components["schemas"]["VisibilityEnum"];
            /** Format: uuid */
            readonly owner: string;
            readonly pages: string[];
        };
        Page: {
            /** Format: uuid */
            readonly id: string;
            assets: {
                [key: string]: components["schemas"]["AssetRef"];
            };
            preview?: components["schemas"]["AssetRef"] | null;
            export?: {
                [key: string]: unknown;
            } | null;
            sceneData?: components["schemas"]["ExcalidrawSceneData"];
            usedStickerIds?: string[];
            schemaVersion?: number;
            /** Format: date-time */
            readonly createdAt: string;
            /** Format: date-time */
            readonly updatedAt: string;
            /** Format: date-time */
            deletedAt?: string | null;
            type?: components["schemas"]["PageTypeEnum"];
            /** Format: date */
            date: string;
            title?: string;
            note?: string;
            tags?: unknown;
            layoutMode?: string;
            layoutSettings?: unknown;
            /** Format: uuid */
            readonly owner: string;
        };
        /**
         * @description * `diary` - Diary
         *     * `schedule` - Schedule
         *     * `free` - Free
         * @enum {string}
         */
        PageTypeEnum: "diary" | "schedule" | "free";
        /** @description 展示物（編集/管理用）。画像はS3 URL（string）を想定。 */
        PatchedExhibit: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            gallery?: string;
            /** Format: uuid */
            readonly owner?: string | null;
            readonly guestId?: string | null;
            slotIndex?: number;
            /** Format: uri */
            imageOriginalUrl?: string;
            /** Format: uri */
            imageCutoutPngUrl?: string | null;
            materialParams?: unknown;
            style?: string;
            title?: string;
            description?: string;
            /** Format: date-time */
            readonly createdAt?: string;
            /** Format: date-time */
            readonly updatedAt?: string;
        };
        /** @description ギャラリー（編集/管理用）。retrieveではexhibitsも返す。 */
        PatchedGallery: {
            /** Format: uuid */
            readonly id?: string;
            slug?: string;
            userStyle?: components["schemas"]["UserStyleEnum"];
            /** Format: uuid */
            readonly owner?: string | null;
            readonly guestId?: string | null;
            title?: string;
            layoutCols?: number;
            layoutRows?: number;
            isPublic?: boolean;
            /** Format: uri */
            coverRenderUrl?: string | null;
            /** Format: date-time */
            readonly createdAt?: string;
            /** Format: date-time */
            readonly updatedAt?: string;
            readonly exhibits?: components["schemas"]["Exhibit"][];
        };
        PatchedNotebook: {
            /** Format: uuid */
            readonly id?: string;
            cover?: components["schemas"]["AssetRef"] | null;
            readonly pageIds?: string[];
            schemaVersion?: number;
            /** Format: date-time */
            readonly createdAt?: string;
            /** Format: date-time */
            readonly updatedAt?: string;
            /** Format: date-time */
            deletedAt?: string | null;
            title?: string;
            description?: string;
            tags?: unknown;
            viewSettings?: unknown;
            visibility?: components["schemas"]["VisibilityEnum"];
            /** Format: uuid */
            readonly owner?: string;
            readonly pages?: string[];
        };
        PatchedPage: {
            /** Format: uuid */
            readonly id?: string;
            assets?: {
                [key: string]: components["schemas"]["AssetRef"];
            };
            preview?: components["schemas"]["AssetRef"] | null;
            export?: {
                [key: string]: unknown;
            } | null;
            sceneData?: components["schemas"]["ExcalidrawSceneData"];
            usedStickerIds?: string[];
            schemaVersion?: number;
            /** Format: date-time */
            readonly createdAt?: string;
            /** Format: date-time */
            readonly updatedAt?: string;
            /** Format: date-time */
            deletedAt?: string | null;
            type?: components["schemas"]["PageTypeEnum"];
            /** Format: date */
            date?: string;
            title?: string;
            note?: string;
            tags?: unknown;
            layoutMode?: string;
            layoutSettings?: unknown;
            /** Format: uuid */
            readonly owner?: string;
        };
        PatchedSchedule: {
            /** Format: uuid */
            readonly id?: string;
            assets?: {
                [key: string]: components["schemas"]["AssetRef"];
            };
            preview?: components["schemas"]["AssetRef"] | null;
            sceneData?: components["schemas"]["ExcalidrawSceneData"];
            schemaVersion?: number;
            /** Format: date-time */
            readonly createdAt?: string;
            /** Format: date-time */
            readonly updatedAt?: string;
            /** Format: date-time */
            deletedAt?: string | null;
            /** @default monthly */
            type: components["schemas"]["ScheduleTypeEnum"];
            /** Format: date */
            startDate?: string;
            title?: string;
            eventsData?: unknown;
            /** Format: uuid */
            readonly owner?: string;
        };
        PatchedSticker: {
            /** Format: uuid */
            readonly id?: string;
            png?: components["schemas"]["AssetRef"];
            thumb?: components["schemas"]["AssetRef"] | null;
            style?: unknown;
            /** @description タグの配列 */
            tags?: string[];
            schemaVersion?: number;
            /** Format: date-time */
            readonly createdAt?: string;
            /** Format: date-time */
            readonly updatedAt?: string;
            /** Format: date-time */
            deletedAt?: string | null;
            name?: string;
            favorite?: boolean;
            /** Format: date-time */
            lastUsedAt?: string | null;
            readonly usageCount?: number;
            isSystem?: boolean;
            width?: number;
            height?: number;
            cropSource?: unknown;
            /** Format: uuid */
            readonly owner?: string;
        };
        PatchedUser: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: email */
            email?: string;
            displayName?: string;
            avatar?: unknown;
            readonly stripeCustomerId?: string | null;
            readonly subscriptionStatus?: string;
            plan?: string;
        };
        Schedule: {
            /** Format: uuid */
            readonly id: string;
            assets: {
                [key: string]: components["schemas"]["AssetRef"];
            };
            preview?: components["schemas"]["AssetRef"] | null;
            sceneData?: components["schemas"]["ExcalidrawSceneData"];
            schemaVersion?: number;
            /** Format: date-time */
            readonly createdAt: string;
            /** Format: date-time */
            readonly updatedAt: string;
            /** Format: date-time */
            deletedAt?: string | null;
            /** @default monthly */
            type: components["schemas"]["ScheduleTypeEnum"];
            /** Format: date */
            startDate: string;
            title?: string;
            eventsData?: unknown;
            /** Format: uuid */
            readonly owner: string;
        };
        /**
         * @description * `monthly` - Monthly
         *     * `weekly` - Weekly
         *     * `daily` - Daily
         * @enum {string}
         */
        ScheduleTypeEnum: "monthly" | "weekly" | "daily";
        Sticker: {
            /** Format: uuid */
            readonly id: string;
            png: components["schemas"]["AssetRef"];
            thumb?: components["schemas"]["AssetRef"] | null;
            style: unknown;
            /** @description タグの配列 */
            tags?: string[];
            schemaVersion?: number;
            /** Format: date-time */
            readonly createdAt: string;
            /** Format: date-time */
            readonly updatedAt: string;
            /** Format: date-time */
            deletedAt?: string | null;
            name?: string;
            favorite?: boolean;
            /** Format: date-time */
            lastUsedAt?: string | null;
            readonly usageCount: number;
            isSystem?: boolean;
            width: number;
            height: number;
            cropSource?: unknown;
            /** Format: uuid */
            readonly owner: string;
        };
        TokenObtainPair: {
            email: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        /** @description アップロード完了報告（クライアント→サーバー） */
        UploadConfirm: {
            /** Format: uuid */
            uploadSessionId: string;
        };
        /** @description アップロード開始要求（クライアント→サーバー） */
        UploadIssue: {
            filename: string;
            mimeType: string;
            purpose: string;
        };
        User: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            email: string;
            displayName?: string;
            avatar?: unknown;
            readonly stripeCustomerId: string | null;
            readonly subscriptionStatus: string;
            plan?: string;
        };
        UserRegistration: {
            /** Format: email */
            email: string;
            password: string;
            displayName?: string;
        };
        /**
         * @description * `user` - User
         *     * `guest` - Guest
         * @enum {string}
         */
        UserStyleEnum: "user" | "guest";
        /**
         * @description * `private` - Private
         *     * `friends` - Friends Only
         *     * `public` - Public
         * @enum {string}
         */
        VisibilityEnum: "private" | "friends" | "public";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_guest_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestIssueResponse"];
                };
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegistration"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRegistration"];
                "multipart/form-data": components["schemas"]["UserRegistration"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRegistration"];
                };
            };
        };
    };
    exhibits_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exhibit"][];
                };
            };
        };
    };
    exhibits_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Exhibit"];
                "application/x-www-form-urlencoded": components["schemas"]["Exhibit"];
                "multipart/form-data": components["schemas"]["Exhibit"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exhibit"];
                };
            };
        };
    };
    exhibits_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this exhibit. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exhibit"];
                };
            };
        };
    };
    exhibits_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this exhibit. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Exhibit"];
                "application/x-www-form-urlencoded": components["schemas"]["Exhibit"];
                "multipart/form-data": components["schemas"]["Exhibit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exhibit"];
                };
            };
        };
    };
    exhibits_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this exhibit. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    exhibits_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this exhibit. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedExhibit"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedExhibit"];
                "multipart/form-data": components["schemas"]["PatchedExhibit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exhibit"];
                };
            };
        };
    };
    galleries_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gallery"][];
                };
            };
        };
    };
    galleries_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Gallery"];
                "application/x-www-form-urlencoded": components["schemas"]["Gallery"];
                "multipart/form-data": components["schemas"]["Gallery"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gallery"];
                };
            };
        };
    };
    galleries_exhibits_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gallery_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Exhibit"];
                "application/x-www-form-urlencoded": components["schemas"]["Exhibit"];
                "multipart/form-data": components["schemas"]["Exhibit"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exhibit"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Slot already occupied */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    galleries_exhibits_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gallery_id: string;
                slot_index: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Exhibit"];
                "application/x-www-form-urlencoded": components["schemas"]["Exhibit"];
                "multipart/form-data": components["schemas"]["Exhibit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exhibit"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exhibit"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    galleries_exhibits_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gallery_id: string;
                slot_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    galleries_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this gallery. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gallery"];
                };
            };
        };
    };
    galleries_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this gallery. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Gallery"];
                "application/x-www-form-urlencoded": components["schemas"]["Gallery"];
                "multipart/form-data": components["schemas"]["Gallery"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gallery"];
                };
            };
        };
    };
    galleries_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this gallery. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    galleries_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this gallery. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedGallery"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedGallery"];
                "multipart/form-data": components["schemas"]["PatchedGallery"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gallery"];
                };
            };
        };
    };
    galleries_g_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GalleryPublic"];
                };
            };
        };
    };
    me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["User"];
                "application/x-www-form-urlencoded": components["schemas"]["User"];
                "multipart/form-data": components["schemas"]["User"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUser"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUser"];
                "multipart/form-data": components["schemas"]["PatchedUser"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    notebooks_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notebook"][];
                };
            };
        };
    };
    notebooks_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Notebook"];
                "application/x-www-form-urlencoded": components["schemas"]["Notebook"];
                "multipart/form-data": components["schemas"]["Notebook"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notebook"];
                };
            };
        };
    };
    notebooks_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this notebook. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notebook"];
                };
            };
        };
    };
    notebooks_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this notebook. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Notebook"];
                "application/x-www-form-urlencoded": components["schemas"]["Notebook"];
                "multipart/form-data": components["schemas"]["Notebook"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notebook"];
                };
            };
        };
    };
    notebooks_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this notebook. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    notebooks_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this notebook. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedNotebook"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedNotebook"];
                "multipart/form-data": components["schemas"]["PatchedNotebook"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notebook"];
                };
            };
        };
    };
    notebooks_pages_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this notebook. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notebook"];
                };
            };
        };
    };
    pages_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"][];
                };
            };
        };
    };
    pages_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Page"];
                "application/x-www-form-urlencoded": components["schemas"]["Page"];
                "multipart/form-data": components["schemas"]["Page"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
        };
    };
    pages_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this page. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
        };
    };
    pages_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this page. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Page"];
                "application/x-www-form-urlencoded": components["schemas"]["Page"];
                "multipart/form-data": components["schemas"]["Page"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
        };
    };
    pages_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this page. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pages_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this page. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPage"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPage"];
                "multipart/form-data": components["schemas"]["PatchedPage"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
        };
    };
    schedules_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"][];
                };
            };
        };
    };
    schedules_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Schedule"];
                "application/x-www-form-urlencoded": components["schemas"]["Schedule"];
                "multipart/form-data": components["schemas"]["Schedule"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
        };
    };
    schedules_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this schedule. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
        };
    };
    schedules_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this schedule. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Schedule"];
                "application/x-www-form-urlencoded": components["schemas"]["Schedule"];
                "multipart/form-data": components["schemas"]["Schedule"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
        };
    };
    schedules_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this schedule. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    schedules_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this schedule. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSchedule"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSchedule"];
                "multipart/form-data": components["schemas"]["PatchedSchedule"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
        };
    };
    stickers_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sticker"][];
                };
            };
        };
    };
    stickers_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Sticker"];
                "application/x-www-form-urlencoded": components["schemas"]["Sticker"];
                "multipart/form-data": components["schemas"]["Sticker"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sticker"];
                };
            };
        };
    };
    stickers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this sticker. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sticker"];
                };
            };
        };
    };
    stickers_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this sticker. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Sticker"];
                "application/x-www-form-urlencoded": components["schemas"]["Sticker"];
                "multipart/form-data": components["schemas"]["Sticker"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sticker"];
                };
            };
        };
    };
    stickers_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this sticker. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stickers_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this sticker. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSticker"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSticker"];
                "multipart/form-data": components["schemas"]["PatchedSticker"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sticker"];
                };
            };
        };
    };
    token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    uploads_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadIssue"];
                "application/x-www-form-urlencoded": components["schemas"]["UploadIssue"];
                "multipart/form-data": components["schemas"]["UploadIssue"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadConfirm"];
                };
            };
        };
    };
}
