# 手順1で作ったベースイメージを参照する
FROM 563224521754.dkr.ecr.ap-northeast-1.amazonaws.com/web-diary/crop-sam2-lambda:latest



# 5. モデル重みのダウンロード
RUN mkdir -p /var/task/models && \
    curl -L https://dl.fbaipublicfiles.com/segment_anything_2/072424/sam2_hiera_tiny.pt \
    -o /var/task/models/sam2_hiera_tiny.pt

COPY lambda_function.py ${LAMBDA_TASK_ROOT}

CMD ["lambda_function.lambda_handler"]
