name: Deploy to App Runner

on:
  push:
    branches: [ develop ]
    paths:
      - 'DjangoAPI/**/*.py' # Python関連が変わった時だけ実行
      - 'DjangoAPI/Dockerfile'
      - ".github/workflows/generate_schema.yml"
      - ".github/workflows/push-ecr-and-deploy-apprunner.yml"





# ★OIDCに必須：一時的なトークンを発行する権限

permissions:
  id-token: write
  contents: read


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
    env:
      STAGE: ${{ vars.STAGE }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      PROJECT_NAME: ${{ vars.PROJECT_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ap-northeast-1
          role-session-name: gha-apprunner

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: web-diary/backend-django
          CONTEXT_DIR: DjangoAPI
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest $CONTEXT_DIR
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Deploy to App Runner
        if: github.ref == 'refs/heads/develop' # developブランチへのpushのときだけ実行
        run: |
          aws apprunner start-deployment --service-arn ${{ secrets.APPRUNNER_SERVICE_ARN }}