name: rembg-isnet-lambda-build

on:
  push:
    branches: ["main"]
    paths:
      - "LambdaContainers/LambdaRembgIsnet/**"
      - ".github/workflows/rembg-isnet-push-ecr.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1
  ECR_REPO: web-diary/rembg/isnet # ECRリポジトリ名
  LAMBDA_FUNCTION_NAME: "rembg_isnet_general rembg_isnet_anime rembg_birefnet_lite" # Lambda関数名

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./LambdaContainers/Lambda_RembgIsnet

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Rembg image
        id: build-image
        uses: docker/build-push-action@v6
        with:
          context: ./LambdaContainers/Lambda_RembgIsnet
          file: ./LambdaContainers/Lambda_RembgIsnet/Dockerfile
          push: true
          provenance: false
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:latest
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Mutiple Lambda function
        run: |
          for FUNCTION_NAME in ${{ env.LAMBDA_FUNCTION_NAMES }}; do
            echo "Updating Lambda function: $FUNCTION_NAME"
            aws lambda update-function-code \
              --function-name $FUNCTION_NAME \
              --image-uri ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:latest
          done